package com.example.rexray_vision

import android.content.SharedPreferences

class NamingManager(private val sharedPreferences: SharedPreferences) {

    private val adjectives = arrayOf("Aero", "Agile", "Alloy", "Ample", "Aloft", "Aqua", "Arid", "Artic", "Aura", "Avid", "Bald", "Brave", "Brief", "Brisk", "Broad", "Buff", "Blunt", "Bold", "Bossy", "Brash", "Calm", "Chic", "Chill", "Clean", "Clear", "Clever", "Cold", "Cool", "Cosmic", "Crisp", "Dandy", "Dapper", "Dark", "Dashing", "Deep", "Deft", "Dense", "Dimin", "Distant", "Divine", "Eager", "Earnest", "Earth", "Easy", "Elite", "Epic", "Equal", "Even", "Exact", "Expert", "Fair", "Fancy", "Fast", "Feral", "Fierce", "Fine", "Firm", "Flat", "Fluid", "Focal", "Free", "Fresh", "Frigid", "Frisky", "Frost", "Funky", "Funny", "Fuzzy", "Gauzy", "Gentle", "Giddy", "Glad", "Glassy", "Gleam", "Glitzy", "Glossy", "Glowing", "Grand", "Great", "Green", "Grim", "Grit", "Groovy", "Grumpy", "Hardy", "Harsh", "Hasty", "Heavy", "Heroic", "High", "Hollow", "Holy", "Hot", "Huge", "Humble", "Hyper", "Icy", "Ideal", "Inner", "Ionic", "Jade", "Jaunty", "Jolly", "Jovial", "Joyful", "Juicy", "Just", "Keen", "Kind", "Lacy", "Large", "Last", "Late", "Lean", "Light", "Lively", "Lofty", "Lone", "Long", "Loud", "Loyal", "Lucid", "Lucky", "Lunar", "Lush", "Lyric", "Magic", "Main", "Major", "Mellow", "Merry", "Mighty", "Mild", "Minty", "Misty", "Modern", "Modest", "Moral", "Moxie", "Mute", "Mystic", "Nifty", "Nimble", "Noble", "Noisy", "North", "Novel", "Oaken", "Ocean", "Odd", "Outer", "Pale", "Peace", "Peppy", "Plain", "Plucky", "Plush", "Polar", "Posh", "Prime", "Proud", "Pure", "Quaint", "Quick", "Quiet", "Quirky", "Rad", "Rapid", "Rare", "Ready", "Real", "Regal", "Rich", "Right", "Riper", "Rizzy", "Robust", "Rough", "Royal", "Rural", "Rusty", "Sable", "Safe", "Salty", "Sane", "Savvy", "Sharp", "Sheer", "Shiny", "Short", "Shy", "Silk", "Silly", "Silver", "Sleek", "Slick", "Slim", "Smart", "Smug", "Snappy", "Sneak", "Snowy", "Solid", "Solar", "Sonic", "Sound", "Spry", "Stark", "Steady", "Stellar")
    private val nouns = arrayOf("Abyss", "Anchor", "Angle", "Anvil", "Apex", "Apple", "Arcade", "Arch", "Arrow", "Aster", "Atlas", "Atom", "Axel", "Axis", "Badge", "Baker", "Ball", "Banner", "Basin", "Beacon", "Beam", "Bell", "Belt", "Bench", "Berry", "Bevel", "Blade", "Block", "Bloom", "Board", "Bolt", "Bonus", "Boom", "Boost", "Boot", "Boxer", "Brace", "Brick", "Bridge", "Brush", "Bubble", "Bucket", "Bugle", "Bulb", "Button", "Cabin", "Cable", "Cactus", "Cage", "Cake", "Camp", "Canyon", "Canvas", "Capsule", "Cargo", "Case", "Castle", "Cedar", "Chain", "Chalk", "Chart", "Chess", "Chime", "Chip", "Cinder", "Circle", "Cliff", "Clock", "Cloud", "Coast", "Cobalt", "Code", "Coil", "Comet", "Compass", "Cone", "Copper", "Core", "Cove", "Crag", "Crane", "Crater", "Creek", "Crest", "Cube", "Cycle", "Dart", "Dash", "Deck", "Delta", "Dial", "Dice", "Digit", "Disk", "Dock", "Dome", "Door", "Dose", "Drift", "Drum", "Dune", "Dust", "Echo", "Edge", "Engine", "Epoch", "Era", "Facet", "Factor", "Field", "File", "Filter", "Flare", "Flash", "Flask", "Fleet", "Flight", "Float", "Flux", "Focus", "Fog", "Forge", "Fork", "Fort", "Frame", "Frost", "Fuel", "Fuse", "Gable", "Gadget", "Gala", "Gasket", "Gate", "Gauge", "Gear", "Gem", "Ghost", "Gizmo", "Glass", "Glide", "Glow", "Glyph", "Goal", "Gold", "Gorge", "Graph", "Grid", "Grip", "Grit", "Grove", "Guard", "Guide", "Gulf", "Gully", "Halo", "Hammer", "Hatch", "Haven", "Haze", "Helix", "Helm", "Hinge", "Hollow", "Hook", "Hub", "Icon", "Idea", "Index", "Inlet", "Iron", "Island", "Item", "Jade", "Jar", "Jet", "Joint", "Jolt", "Key", "Kite", "Knack", "Knot", "Label", "Lake", "Lamp", "Lane", "Latch", "Lava", "Leaf", "Lens", "Level", "Link", "List", "Lock", "Logic", "Loop", "Lumen", "Lunar", "Magnet", "Map", "Mask")
    private val animals = arrayOf("Antelope", "Ape", "Armadillo", "Ass", "Baboon", "Badger", "Bandicoot", "Bat", "Beagle", "Bear", "Beaver", "Bison", "Boar", "Bobcat", "Bongo", "Bonobo", "Boxer", "Buck", "Buffalo", "Bull", "Bunny", "Burro", "Camel", "Canine", "Capybara", "Caracal", "Caribou", "Cat", "Cattle", "Chamois", "Cheetah", "Chimp", "Chipmunk", "Civet", "Coati", "Collie", "Colt", "Cougar", "Cow", "Coyote", "Cuscus", "Dachsy", "Deer", "Dingo", "Dog", "Donkey", "Dormouse", "Drill", "Dugong", "Duiker", "Echidna", "Eland", "Elk", "Ermine", "Ewe", "Fawn", "Fennec", "Ferret", "Fillie", "Fisher", "Foal", "Fossa", "Fox", "Gazelle", "Genet", "Gerbil", "Gibbon", "Giraffe", "Gnu", "Goat", "Gopher", "Gorilla", "Grizzly", "Guanaco", "Hamster", "Hare", "Hedgehog", "Heifer", "Hippo", "Hog", "Horse", "Hound", "Hyena", "Hyrax", "Ibex", "Impala", "Jackal", "Jaguar", "Jerboa", "Joey", "Kangaroo", "Kid", "Kitten", "Koala", "Kodu", "Kudu", "Lamb", "Lemur", "Leo", "Leopard", "Liger", "Lion", "Llama", "Loris", "Lynx", "Maki", "Mammoth", "Manatee", "Mandrill", "Mara", "Marten", "Meerkat", "Mink", "Mole", "Mongoose", "Monkey", "Moose", "Mouse", "Mule", "Muntjac", "Muskox", "Muskrat", "Narwhal", "Newt", "Nilgai", "Numbat", "Nutria", "Nyala", "Ocelot", "Okapi", "Opossum", "Orca", "Oribi", "Oryx", "Otter", "Ounce", "Ox", "Panda", "Pangolin", "Panther", "Peccary", "Pig", "Piglet", "Pika", "Platypus", "Pony", "Porpoise", "Possum", "Pug", "Puma", "Puppy", "Quagga", "Quokka", "Quoll", "Rabbit", "Raccoon", "Ram", "Rat", "Ratel", "Reindeer", "Rhino", "Roebuck", "Sable", "Seal", "Serval", "Sheep", "Shrew", "Siamang", "Skunk", "Sloth", "Sow", "Spaniel", "Springbok", "Squirrel", "Stag", "Steer", "Stoat", "Sus", "Tahr", "Tamarin", "Tapir", "Tarsier", "Tenrec", "Tiger", "Tiglon", "Titi", "Urial", "Vicuna", "Vole", "Wallaby", "Walrus", "Wapiti", "Warthog", "Waterbuck", "Weasel", "Whale", "Wildcat", "Wolf", "Wolverine", "Wombat", "Woodchuck", "Yak", "Zebra", "Zebu", "Zorilla")

    fun setupNewProject(force: Boolean): String {
        var pName = if (force) null else sharedPreferences.getString("projectName", null)
        if (pName == null) {
            pName = "${adjectives.random()}-${nouns.random()}"
            sharedPreferences.edit().putString("projectName", pName).apply()
        }
        return pName
    }

    fun generateCameraName(force: Boolean): String {
        var aName = sharedPreferences.getString("cameraName", null)
        if (aName == null || force) {
            aName = animals.random()
            sharedPreferences.edit().putString("cameraName", aName).apply()
        }
        return aName
    }
}
